/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/materiales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo completo de materiales propios de la empresa (incluye consumibles y activos).
         * @description Requiere el scope `materiales:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listMateriales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materiales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un material del catálogo.
         * @description Requiere el scope `materiales:read`.
         */
        get: operations["getMaterial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Productos: consumibles y repuestos, lo que se compra por cantidad.
         * @description Requiere el scope `productos:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listProductos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un producto.
         * @description Requiere el scope `productos:read`.
         */
        get: operations["getProducto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proveedores de la empresa (los eliminados vienen con `activo: false`).
         * @description Requiere el scope `proveedores:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listProveedores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un proveedor.
         * @description Requiere el scope `proveedores:read`.
         */
        get: operations["getProveedor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activos con identidad propia (equipos, herramientas, TI, reutilizables).
         * @description Requiere el scope `activos:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listActivos"];
        put?: never;
        /**
         * Crea UNA unidad rastreable al recibirla (una llamada por unidad).
         * @description Requiere `activos:write`. Copia los datos del ítem del catálogo, le asigna código y QR propios, y la deja en el pañol indicado. No genera gasto en Pagnol: el gasto vive en el sistema que compró. Repetir la misma `external_ref` devuelve el activo ya creado (200).
         */
        post: operations["createActivo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un activo.
         * @description Requiere el scope `activos:read`.
         */
        get: operations["getActivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambia el estado y/o la ubicación de un activo.
         * @description Requiere `activos:write`. `de_baja` lo marca para baja (no borra nada). Un activo archivado en Pagnol responde 409.
         */
        patch: operations["patchActivo"];
        trace?: never;
    };
    "/panoles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pañoles (bodegas) de la empresa, con los contratos que atienden.
         * @description Requiere `activos:read`, `materiales:read` o `productos:read`. Una sola página.
         */
        get: operations["listPanoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materiales/{id}/existencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cuánto hay de un material (o activo) en cada pañol y contrato.
         * @description Requiere `materiales:read`, `productos:read` o `activos:read`.
         */
        get: operations["getExistencias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingresa stock de un consumible al recibirlo, o revierte un ingreso.
         * @description Requiere `stock:write`. Sólo materiales NO rastreables. Un reverso es un movimiento nuevo que descuenta lo ingresado (nunca se borra el original); si esas unidades ya se entregaron o movieron, responde 409 y se ajusta en Pagnol. No genera gasto en Pagnol.
         */
        post: operations["createMovimiento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Material: {
            /** Format: uuid */
            id: string;
            /** @description Código interno; si no tiene, el N° de serie; si tampoco, el id. Es el mismo valor que lleva la etiqueta QR. */
            codigo: string;
            nombre: string;
            descripcion: string | null;
            categoria: string | null;
            /** @description Unidad tal como se registró en el catálogo (texto libre). */
            unidad_medida: string;
            /** @description Total de la empresa, sumando todos los contratos y pañoles. */
            stock_actual: number | null;
            stock_minimo: number | null;
            /** @description `false` si el material fue archivado o eliminado. */
            activo: boolean;
            /** @description `true`: cada unidad es un activo con su propio código y QR; al recibirlo se crea con `POST /activos`, una llamada por unidad. `false`: se controla por cantidad; al recibirlo se ingresa con `POST /movimientos`. */
            rastreable: boolean;
            /** @description Tipo de uso tal como está en Pagnol (ej. "Herramienta Menor", "Consumible"). */
            tipo_uso: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        MaterialList: {
            data: components["schemas"]["Material"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "validation_error" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "idempotency_conflict" | "rate_limited" | "internal_error";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ProductoList: {
            data: components["schemas"]["Material"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Proveedor: {
            /** Format: uuid */
            id: string;
            rut: string | null;
            razon_social: string;
            nombre_fantasia: string | null;
            email: string | null;
            telefono: string | null;
            /** @description `false` si el proveedor fue eliminado. */
            activo: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        ProveedorList: {
            data: components["schemas"]["Proveedor"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        /** @description Pañol donde está. `null` si está prestado, sin pañol asignado, o repartido en varios lugares (ver `/materiales/{id}/existencias`). */
        Ref: {
            /** Format: uuid */
            id: string;
            nombre: string;
        } | null;
        Activo: {
            /** Format: uuid */
            id: string;
            /** @description El valor que lleva la etiqueta QR del activo. */
            codigo: string;
            nombre: string;
            /**
             * Format: uuid
             * @description Ítem del catálogo desde el que se creó esta unidad (`POST /activos`). `null` en los activos cargados directamente en Pagnol.
             */
            material_id: string | null;
            /** Format: uuid */
            proveedor_id: string | null;
            /** @enum {string} */
            estado: "operativo" | "en_mantencion" | "de_baja" | "extraviado";
            /** @description Ubicación descriptiva (texto libre). */
            ubicacion: string | null;
            panol: components["schemas"]["Ref"];
            contrato: components["schemas"]["Ref"] & unknown;
            /** @description Quién lo tiene en su poder (última entrega sin devolución). `null` si está en el pañol. */
            responsable: string | null;
            valor_compra: number | null;
            /** @description Fecha (YYYY-MM-DD). */
            fecha_compra: string | null;
            /** @description Referencia del sistema que originó el activo (ej. `valar:recepcion:…:unidad:2`). */
            external_ref: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        ActivoList: {
            data: components["schemas"]["Activo"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Panol: {
            /** Format: uuid */
            id: string;
            nombre: string;
            ubicacion: string | null;
            /** @description `false` si el pañol está inactivo (no recibe ingresos). */
            activo: boolean;
            /** @description Contratos que atiende el pañol. */
            contratos: (components["schemas"]["Ref"] & Record<string, never>)[];
        };
        PanolList: {
            data: components["schemas"]["Panol"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Existencias: {
            /** Format: uuid */
            material_id: string;
            stock_actual: number | null;
            existencias: {
                panol: components["schemas"]["Ref"] & unknown;
                contrato: components["schemas"]["Ref"] & unknown;
                cantidad: number;
            }[];
        };
        CreateActivo: {
            /**
             * Format: uuid
             * @description Ítem rastreable del catálogo (`rastreable: true` en `/materiales`). La unidad copia sus datos.
             */
            material_id: string;
            /** @description Por defecto, el nombre del ítem del catálogo. */
            nombre?: string;
            /** Format: uuid */
            proveedor_id?: string | null;
            valor_compra?: number | null;
            /** @description Fecha de recepción (YYYY-MM-DD). Por defecto, hoy. */
            fecha_compra?: string;
            ubicacion?: string | null;
            /**
             * Format: uuid
             * @description Pañol donde queda (ver `/panoles`). Sin él, queda sin pañol asignado.
             */
            panol_id?: string | null;
            /** @description Referencia única del sistema que origina la operación. Repetirla devuelve lo ya creado, nunca duplica. */
            external_ref: string;
        };
        PatchActivo: {
            /** @enum {string} */
            estado?: "operativo" | "en_mantencion" | "extraviado" | "de_baja";
            ubicacion?: string | null;
        };
        Movimiento: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            tipo: "ingreso" | "reverso";
            /** Format: uuid */
            material_id: string;
            /** @description Unidades ingresadas (o revertidas), siempre positivo. */
            cantidad: number;
            /** @description Stock total del material después del movimiento. */
            stock_actual: number;
            /** @description En un reverso, la referencia del ingreso revertido. */
            external_ref: string;
        };
        CreateMovimiento: {
            /** @enum {string} */
            tipo: "ingreso";
            /**
             * Format: uuid
             * @description Material NO rastreable (`rastreable: false`).
             */
            material_id: string;
            cantidad: number;
            /** @description Fecha de la recepción (ISO 8601 o YYYY-MM-DD). Por defecto, ahora. */
            fecha?: string;
            /**
             * Format: uuid
             * @description Pañol donde entra (ver `/panoles`). Sin él, entra sin pañol asignado.
             */
            panol_id?: string | null;
            /** @description Referencia única del sistema que origina la operación. Repetirla devuelve lo ya creado, nunca duplica. */
            external_ref: string;
        } | {
            /** @enum {string} */
            tipo: "reverso";
            /** @description La `external_ref` del ingreso que se revierte. */
            external_ref: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMateriales: {
        parameters: {
            query?: {
                q?: string;
                categoria?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Material"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProductos: {
        parameters: {
            query?: {
                q?: string;
                categoria?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProducto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Material"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProveedores: {
        parameters: {
            query?: {
                q?: string;
                rut?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProveedor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proveedor"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listActivos: {
        parameters: {
            query?: {
                q?: string;
                estado?: "operativo" | "en_mantencion" | "de_baja" | "extraviado";
                material_id?: string;
                external_ref?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createActivo: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateActivo"];
            };
        };
        responses: {
            /** @description Ya existía un activo con esa `external_ref`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activo"];
                };
            };
            /** @description Activo creado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activo"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description El material, pañol, proveedor o activo no existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `idempotency_conflict` (misma llave, otro cuerpo) o `conflict` (external_ref ya usada para otra cosa, petición en curso, o reverso imposible). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getActivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activo"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patchActivo: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchActivo"];
            };
        };
        responses: {
            /** @description Activo actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activo"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description El material, pañol, proveedor o activo no existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `idempotency_conflict` (misma llave, otro cuerpo) o `conflict` (external_ref ya usada para otra cosa, petición en curso, o reverso imposible). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPanoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pañoles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanolList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getExistencias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existencias. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Existencias"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createMovimiento: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateMovimiento"];
            };
        };
        responses: {
            /** @description Ya existía con esa `external_ref`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movimiento"];
                };
            };
            /** @description Movimiento registrado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movimiento"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description El material, pañol, proveedor o activo no existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `idempotency_conflict` (misma llave, otro cuerpo) o `conflict` (external_ref ya usada para otra cosa, petición en curso, o reverso imposible). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
