/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/materiales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo completo de materiales propios de la empresa (incluye consumibles y activos).
         * @description Requiere el scope `materiales:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listMateriales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materiales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un material del catálogo.
         * @description Requiere el scope `materiales:read`.
         */
        get: operations["getMaterial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Productos: consumibles y repuestos, lo que se compra por cantidad.
         * @description Requiere el scope `productos:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listProductos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un producto.
         * @description Requiere el scope `productos:read`.
         */
        get: operations["getProducto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proveedores de la empresa (los eliminados vienen con `activo: false`).
         * @description Requiere el scope `proveedores:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listProveedores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proveedores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un proveedor.
         * @description Requiere el scope `proveedores:read`.
         */
        get: operations["getProveedor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activos con identidad propia (equipos, herramientas, TI, reutilizables).
         * @description Requiere el scope `activos:read`. Orden por `updated_at` ascendente; paginación por cursor.
         */
        get: operations["listActivos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Un activo.
         * @description Requiere el scope `activos:read`.
         */
        get: operations["getActivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Material: {
            /** Format: uuid */
            id: string;
            /** @description Código interno; si no tiene, el N° de serie; si tampoco, el id. Es el mismo valor que lleva la etiqueta QR. */
            codigo: string;
            nombre: string;
            descripcion: string | null;
            categoria: string | null;
            /** @description Unidad tal como se registró en el catálogo (texto libre). */
            unidad_medida: string;
            /** @description Total de la empresa, sumando todos los contratos y pañoles. */
            stock_actual: number | null;
            stock_minimo: number | null;
            /** @description `false` si el material fue archivado o eliminado. */
            activo: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        MaterialList: {
            data: components["schemas"]["Material"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "validation_error" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "idempotency_conflict" | "rate_limited" | "internal_error";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ProductoList: {
            data: components["schemas"]["Material"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Proveedor: {
            /** Format: uuid */
            id: string;
            rut: string | null;
            razon_social: string;
            nombre_fantasia: string | null;
            email: string | null;
            telefono: string | null;
            /** @description `false` si el proveedor fue eliminado. */
            activo: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        ProveedorList: {
            data: components["schemas"]["Proveedor"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
        Activo: {
            /** Format: uuid */
            id: string;
            /** @description El valor que lleva la etiqueta QR del activo. */
            codigo: string;
            nombre: string;
            /**
             * Format: uuid
             * @description Reservado. Siempre `null` en esta versión.
             */
            material_id: string | null;
            /** Format: uuid */
            proveedor_id: string | null;
            /** @enum {string} */
            estado: "operativo" | "en_mantencion" | "de_baja" | "extraviado";
            ubicacion: string | null;
            /** @description Reservado. Siempre `null` en esta versión. */
            responsable: string | null;
            valor_compra: number | null;
            /** @description Fecha (YYYY-MM-DD). */
            fecha_compra: string | null;
            /** @description Referencia al sistema que originó el activo. Siempre `null` en esta versión. */
            external_ref: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        ActivoList: {
            data: components["schemas"]["Activo"][];
            /** @description `null` cuando no hay más páginas. */
            next_cursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMateriales: {
        parameters: {
            query?: {
                q?: string;
                categoria?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Material"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProductos: {
        parameters: {
            query?: {
                q?: string;
                categoria?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProducto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Material"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listProveedores: {
        parameters: {
            query?: {
                q?: string;
                rut?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProveedorList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProveedor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proveedor"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listActivos: {
        parameters: {
            query?: {
                q?: string;
                estado?: "operativo" | "en_mantencion" | "de_baja" | "extraviado";
                material_id?: string;
                updated_since?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de resultados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivoList"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getActivo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activo"];
                };
            };
            /** @description Parámetros inválidos (`validation_error`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Falta la API key, es inválida o está revocada (`unauthorized`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La API key no tiene el scope requerido (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No existe en la empresa de la API key (`not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de peticiones superado (`rate_limited`). */
            429: {
                headers: {
                    /** @description Segundos a esperar antes de reintentar. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno (`internal_error`). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
